### ISSUE TITLE
Power Supply and other questions

### ISSUE THREAD

**Issue by fritzrichter** [Links2004/arduinoMideaAC#4]
First of all thanks for this project, I want to try it out with my devices pretty soon.
Some questions:

1. I read ([Link](https://rntlab.com/question/can-i-power-esp32-with-5v-via-the-vin-pin/#:~:text=Hello%20Lars%2C%20Yes!,from%205V%20to%203.3V.)) that you actually can power an ESP-32 with 5V via the 5V pin, why is there a need to use a LDO?
2. At OpenHab I saw [an article](https://community.openhab.org/t/tutorial-connect-your-dumb-midea-ac-unit-to-openhab-with-mqtt/114994) and it was said that you need to unsolder the USB connector, is this true? Wouldn't it be easier to just use a male USB connector and wire the 4 pins to that board?
3. My device supports LED (on/off), which is a nice option for the night. I would like to switch it off via my gateway as well, any chance to add support for this as well?

**Comment by Links2004** [comment]
- if your board has a build in LDO (5V pin) you can us this pin, (hint all ESP boards with a USB port have one)
- yes you can simply cut a USB cable or buy a connector and solder to the level shifter and  ESP and you are done, that is how I conneted my ESP8266 to my AC
- are you able to control the LED via the APP? in my case I only where able to control the WIFI connected Symbole and there where no option to disable the display in the APP. If there is one for you then we need to do a MITT on the serial connection to see what needs to be send :)
https://github.com/Links2004/arduinoMideaAC/blob/2120654eee9eb1ad85f145055edb976155c2f474/src/mideaAC.cpp#L28-L31

**Comment by fritzrichter** [comment]
Awesome, thanks for your feedback. I will setup the stuff and give it a try. Will let you know once I have some first results. Need to find out first which cables from the USB to connect where. I never used the app, only the remote, where I actually can enable/disable the LED/Light on the device, maybe it's not supported via the app. I will keep you posted.
