### ISSUE TITLE
JSON format without Array

### ISSUE THREAD

**Issue by njordan77** [Links2004/arduinoMideaAC#6]
Hi,
i'm now using your MQTT example and it works great. Only issue i have is the JSON array format as its not easy to extract to openhab solution. I'm not a superstar in developing code, but it looks like there is an array with only a single field. Would it be possible to remove this array and simply present it like this -  this way its simple to transform in openhab.

Original
`/miAC/state [{"ist":23,"aussen":11,"conf":{"on":false,"turbo":false,"eco":false,"soll":17,"lamelle":false,"mode":5,"fan":0}}]`

Without Array.
`/miAC/state {"ist":23,"aussen":11,"conf":{"on":false,"turbo":false,"eco":false,"soll":17,"lamelle":false,"mode":5,"fan":0}}`

That is also the way how Tasmota or ZigBee2MQTT do their data handling. as i'm not so experienced with JSON at all i do not know it the array variant provides additional advantages.

Thanks for consideration / telling me how i could change it into non Array-based code.
Norbert

**Comment by Links2004** [comment]
the array is created here:
https://github.com/Links2004/arduinoMideaAC/blob/2120654eee9eb1ad85f145055edb976155c2f474/examples/esp32/sendAndReceiveMQTTExample/sendAndReceiveMQTTExample.ino#L49-L51
you can change this the way you like it.

untested example:
```cpp
JsonObject statusObj = doc.to<JsonObject>();
```
the full JSON docu can be found here:
https://arduinojson.org/

**Comment by njordan77** [comment]
Thanks, works perfect.
